# Generated by Django 3.0.3 on 2021-09-15 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='hare krishna', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devotee',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dev', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='devotee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clean.Devotee'),
        ),
    ]
