# Generated by Django 3.0.3 on 2021-09-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0004_service_devotee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(default='hare krishna', max_length=500),
        ),
    ]
